spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#spring:
#  cors:
#    allowed-origins: "*"
#    allowed-methods: "*"
#    allowed-headers: "*"
#    allow-credentials: true
#    max-age: 3600

